export const ABOUT = {
  "id": 1,
  "name": "Ahelan V",
  "bio": "I am a passionate web developer with a strong interest in building clean, responsive, and user-friendly web applications. I enjoy working with modern technologies and continuously improving my skills by learning new tools and frameworks. My goal is to create efficient solutions that deliver great user experiences.",
  "profile_image": "/images/ahelan.jpg.png",
  "email": "ahelanv49@gmail.com",
  "phone": "7200673492",
  "location": "",
  "resume": null,
  "heading_1": "Full-Stack Developer | Python, Django, React & PostgreSQL",
  "heading_2": "Python, Django, React & PostgreSQL",
  "heading_em": "aim",
  "heading_3": "it.",
  "education_text": "MSc International Business \u00b7 Montpellier Business School \u00b7 2024\u20132026 \u00b7 Global Market Intelligence \u00b7 Strategic Leadership \u00b7 AI in Business",
  "cta_text": "Explore My Work",
  "fr_heading_1": "Le design, c\u2019est ma fa\u00e7on de penser \u2014",
  "fr_heading_2": "le business, ma fa\u00e7on de la",
  "fr_heading_em": "diriger",
  "fr_heading_3": ".",
  "fr_education_text": "MSc International Business \u00b7 Montpellier Business School \u00b7 2024\u20132026 \u00b7 Intelligence des march\u00e9s \u00b7 Leadership strat\u00e9gique \u00b7 IA en entreprise",
  "fr_cta_text": "D\u00e9couvrir mes projets",
  "marquee_1": [
    "Product Design",
    "UX Design",
    "UI Design",
    "Design Systems",
    "User Research",
    "Interaction Design",
    "Design Thinking"
  ],
  "marquee_2": [
    "Wireframing",
    "Prototyping",
    "Visual Design",
    "Accessibility",
    "Motion Design",
    "Figma",
    "Framer",
    "AI-Assisted Design",
    "Frontend Development"
  ],
  "metrics": [
    {
      "value": "1st",
      "count": null,
      "label": "Sophia Antipolis Innovation Hackathon \u2014 LockAI",
      "fr_label": "Hackathon Innovation Sophia Antipolis \u2014 LockAI"
    },
    {
      "value": "3+",
      "count": 3,
      "suffix": "+",
      "label": "Years of cross-functional product experience",
      "fr_label": "Ans d\u2019exp\u00e9rience produit transversale"
    },
    {
      "value": "$70K+",
      "count": 70,
      "prefix": "$",
      "suffix": "K+",
      "label": "Revenue generated by conversion-focused work",
      "fr_label": "Revenus g\u00e9n\u00e9r\u00e9s par un travail orient\u00e9 conversion"
    },
    {
      "value": "1B+",
      "count": null,
      "label": "Tonnes of CO\u2082 the product I design aims to avoid by 2050",
      "fr_label": "Tonnes de CO\u2082 que le produit que je con\u00e7ois vise \u00e0 \u00e9viter d\u2019ici 2050"
    }
  ],
  "projects_completed": 14,
  "years_of_experience": 2,
  "countries_worked_with": 0,
  "client_satisfaction": 100,
  "about_metric_1_val": "2+",
  "about_metric_1_title": "Years of Learning",
  "about_metric_1_desc": "Problem solving, DSA and development",
  "about_metric_2_val": "10+",
  "about_metric_2_title": "Projects Completed",
  "about_metric_2_desc": "Web applications built with real-world use cases",
  "about_metric_3_val": "5+",
  "about_metric_3_title": "Technologies",
  "about_metric_3_desc": "Experienced in modern full-stack tools",
  "about_metric_4_val": "100%",
  "about_metric_4_title": "Commitment",
  "about_metric_4_desc": "Focused on writing clean code and delivering quality",
  "updated_at": "2026-08-15T17:34:40.210919+05:30"
};
