export const CERTS = [
  {
    no: "01",
    issuer: "Coimbatore Institute of Technology",
    title: "Hackathon - Mechnotron 2K26",
    year: "2026",
    credential_id: null,
    credential_url: null,
    verified: true,
    skills: ["Hackathon", "Problem Solving", "Technical Symposium"],
    metric_value: null,
    metric_label: null,
    logo_image: "/images/issuers/cit.svg",
    logo_aspect: 1,
    fr_title: "Hackathon - Mechnotron 2K26",
    fr_skills: ["Hackathon", "Résolution de problèmes", "Symposium Technique"],
    fr_metric_label: null,
    order: 1,
  },
  {
    no: "02",
    issuer: "United Institute of Technology",
    title: "Hackathon - UTHRA-2k25",
    year: "2025",
    credential_id: null,
    credential_url: null,
    verified: true,
    skills: ["Hackathon", "Inter College Fest", "Teamwork"],
    metric_value: null,
    metric_label: null,
    logo_image: "/images/issuers/uit.svg",
    logo_aspect: 1,
    fr_title: "Hackathon - UTHRA-2k25",
    fr_skills: ["Hackathon", "Festival Inter-universitaire", "Travail d'équipe"],
    fr_metric_label: null,
    order: 2,
  },
  {
    no: "03",
    issuer: "Pinesphere Solutions Private Limited",
    title: "Internship - Python and Django Web Development",
    year: "2026",
    credential_id: "710724104008",
    credential_url: null,
    verified: true,
    skills: ["Python", "Django", "Database Integration", "Testing", "Deployment"],
    metric_value: "15 May - 30 May",
    metric_label: "Duration",
    logo_image: "/images/issuers/pinesphere.svg",
    logo_aspect: 1,
    fr_title: "Stage - Développement Web Python et Django",
    fr_skills: ["Python", "Django", "Intégration de Bases de Données", "Tests", "Déploiement"],
    fr_metric_label: "Durée",
    order: 3,
  },
  {
    no: "04",
    issuer: "E-Cell, IIT Bombay",
    title: "Illuminate Entrepreneurship Bootcamp",
    year: "2025",
    credential_id: null,
    credential_url: null,
    verified: true,
    skills: ["Entrepreneurship", "Bootcamp", "Innovation"],
    metric_value: null,
    metric_label: null,
    logo_image: "/images/issuers/iitb.svg",
    logo_aspect: 1,
    fr_title: "Bootcamp Entrepreneuriat Illuminate",
    fr_skills: ["Entrepreneuriat", "Bootcamp", "Innovation"],
    fr_metric_label: null,
    order: 4,
  },
  {
    no: "05",
    issuer: "Pinesphere",
    title: "Full Stack with Python and Django (Additional Skills Course)",
    year: "2026",
    credential_id: null,
    credential_url: null,
    verified: true,
    skills: ["Full Stack Development", "Python", "Django"],
    metric_value: "Jan - Feb",
    metric_label: "Duration",
    logo_image: "/images/issuers/pinesphere.svg",
    logo_aspect: 1,
    fr_title: "Full Stack avec Python et Django",
    fr_skills: ["Développement Full Stack", "Python", "Django"],
    fr_metric_label: "Durée",
    order: 5,
  },
];
