export const PROJECTS = [
  {
    "id": 8,
    "title": "Smart City Cleanliness Tracker",
    "description": "The dashboard provides real-time information about complaints, waste collection, bins, and cleanliness hotspots.\r\nCitizens can report issues with photos and locations, while municipal workers can manage and verify cleaning tasks.\r\nAI-powered analytics help identify high-risk areas and track cleanliness trends across the city.\r\nThe system monitors worker performance, complaint resolution, citizen participation, and cleanliness scores.\r\nIt improves transparency, faster response times, and overall cleanliness management for a smart city.",
    "short_description": "Smart City Cleanliness Tracker is a smart municipal platform for monitoring, reporting, and managing cleanliness issues across the city.",
    "image": "/images/projects/reverie-cover.jpg",
    "technology_used": "HTML,SS,Java Scripts,Django,Python",
    "project_url": "https://github.com/ahelan46/Smart_Bin.git",
    "github_url": "https://github.com/ahelan46/Smart_Bin.git",
    "completed_date": "2026-02-14",
    "is_featured": false,
    "created_at": "2026-08-14T15:25:09.302504+05:30",
    "updated_at": "2026-08-14T15:25:09.302504+05:30"
  },
  {
    "id": 7,
    "title": "Client Project Tracker",
    "description": "The dashboard provides a centralized view of all ongoing and completed projects.\r\nIt displays key metrics such as total projects, completed tasks, pending tasks, and clients.\r\nProject managers can monitor task status, project progress, deadlines, and team activities.\r\nThe system also includes messaging, file management, reports, calendar, and payment tracking.\r\nIts modern, responsive interface helps organizations improve productivity, collaboration, and project visibility.",
    "short_description": "Client Project Tracker is a professional project management dashboard designed to manage clients, projects, tasks, teams, deadlines, and payments in one place.",
    "image": "/images/projects/vistarail-cover.jpg",
    "technology_used": "HTML,SS,Java Scripts,Django,Python",
    "project_url": "https://github.com/ahelan46/client_project_tracker.git",
    "github_url": "https://github.com/ahelan46/client_project_tracker.git",
    "completed_date": "2026-06-14",
    "is_featured": false,
    "created_at": "2026-08-14T15:15:05.274586+05:30",
    "updated_at": "2026-08-14T15:15:05.274586+05:30"
  },
  {
    "id": 6,
    "title": "ShopEase \u2013 E-Commerce Web Application",
    "description": "ShopEase is a complete online shopping solution built with a full-stack architecture.\r\nUsers can register, log in, and manage their profiles.\r\nThe platform displays products with categories and filters.\r\nA shopping cart allows users to manage selected items.\r\nSecure checkout functionality processes orders efficiently.\r\nAdmins can add, update, or remove products.\r\nOrder history helps users track previous purchases.\r\nInventory management prevents out-of-stock issues.\r\nSearch functionality improves product discovery.\r\nResponsive design ensures mobile compatibility.\r\nPayment integration can be added easily.\r\nData validation ensures secure transactions.\r\nUser authentication protects personal data.\r\nThe system supports scalable product listings.\r\nShopEase delivers a smooth online shopping experience.",
    "short_description": "ShopEase is a full-stack e-commerce platform for online shopping. It allows users to browse products, add items to cart, and place orders.",
    "image": "/images/projects/habu-cover.jpg",
    "technology_used": "Frontend: HTML, CSS, JavaScript, Bootstrap  Backend: Python, Django  Database: PostgreSQL  Payment: Razorpay / Stripe (Optional)",
    "project_url": "https://www.google.com/search?q=chatgpt&rlz=1C1GCEA_enIN1197IN1197&oq=&gs_lcrp=EgZjaHJvbWUqCQgAECMYJxjqAjIJCAAQIxgnGOoCMgkIARAjGCcY6gIyCQgCECMYJxjqAjIJCAMQIxgnGOoCMgkIBBAjGCcY6gIyCQgFECMYJxjqAjIJCAYQI",
    "github_url": "https://www.google.com/search?q=chatgpt&rlz=1C1GCEA_enIN1197IN1197&oq=&gs_lcrp=EgZjaHJvbWUqCQgAECMYJxjqAjIJCAAQIxgnGOoCMgkIARAjGCcY6gIyCQgCECMYJxjqAjIJCAMQIxgnGOoCMgkIBBAjGCcY6gIyCQgFECMYJxjqAjIJCAYQI",
    "completed_date": "2026-01-28",
    "is_featured": true,
    "created_at": "2026-01-28T17:49:15.678331+05:30",
    "updated_at": "2026-01-28T17:51:58.685730+05:30"
  },
  {
    "id": 5,
    "title": "VoteSphere \u2013 Online Voting System",
    "description": "VoteSphere is a full-stack online voting system designed to replace traditional paper-based elections.\r\nThe system provides secure user authentication to prevent unauthorized access.\r\nEach voter is allowed to vote only once using unique credentials.\r\nAdmins can create elections, add candidates, and manage voters easily.\r\nThe platform uses role-based access for admin and voters.\r\nVotes are stored securely in the database with integrity checks.\r\nThe system displays live vote counts and final results instantly.\r\nIt reduces manual errors and speeds up the election process.\r\nThe UI is responsive and works across devices.\r\nAudit logs help maintain election transparency.\r\nData validation prevents invalid or duplicate votes.\r\nResults can be exported for reporting purposes.\r\nThe system supports multiple elections simultaneously.\r\nSecurity best practices are followed throughout the application.\r\nVoteSphere is ideal for schools, organizations, and institutions.",
    "short_description": "VoteSphere is a secure web-based voting platform that allows users to cast votes digitally. It ensures transparency, accuracy, and real-time result tracking.",
    "image": "/images/projects/got-cover.jpg",
    "technology_used": "Frontend: HTML, CSS, JavaScript, Bootstrap  Backend: Python, Django  Database: SQLite / PostgreSQL  Authentication: Django Auth",
    "project_url": "https://www.google.com/search?q=chatgpt&rlz=1C1GCEA_enIN1197IN1197&oq=&gs_lcrp=EgZjaHJvbWUqCQgAECMYJxjqAjIJCAAQIxgnGOoCMgkIARAjGCcY6gIyCQgCECMYJxjqAjIJCAMQIxgnGOoCMgkIBBAjGCcY6gIyCQgFECMYJxjqAjIJCAYQI",
    "github_url": "https://www.google.com/search?q=chatgpt&rlz=1C1GCEA_enIN1197IN1197&oq=&gs_lcrp=EgZjaHJvbWUqCQgAECMYJxjqAjIJCAAQIxgnGOoCMgkIARAjGCcY6gIyCQgCECMYJxjqAjIJCAMQIxgnGOoCMgkIBBAjGCcY6gIyCQgFECMYJxjqAjIJCAYQI",
    "completed_date": "2026-01-28",
    "is_featured": true,
    "created_at": "2026-01-28T17:48:16.983997+05:30",
    "updated_at": "2026-01-28T17:48:16.984024+05:30"
  },
  {
    "id": 2,
    "title": "to_do _list",
    "description": "The To\u2011Do List application is a smart and intuitive productivity tool designed to help users organize their daily tasks with ease. It allows you to add, edit, and delete tasks quickly, while categorizing them into clear lists for better management. With features like priority settings, deadlines, and reminders, you can stay focused on what matters most and never miss an important activity. A clean and lightweight interface ensures a smooth user experience, while progress tracking helps you visualize accomplishments and stay motivated. The app supports both personal and professional task management, making it versatile for any lifestyle. Syncing across devices keeps your tasks accessible anytime, anywhere, and secure storage ensures your data remains safe. Customizable themes let you personalize the look and feel, while search and filter options make finding tasks effortless. Whether you\u2019re planning your day, managing projects, or setting long\u2011term goals, this app is your reliable companion for staying organized, productive, and in control.",
    "short_description": "\"A simple and intuitive app designed to help users organize tasks, set priorities, and track progress. It allows adding, editing, and categorizing tasks with reminders, ensuring nothing important is missed.\"",
    "image": "/images/projects/avengers-cover.jpg",
    "technology_used": "python django",
    "project_url": "https://github.com/ahelan46/Dealer.git",
    "github_url": "https://github.com/ahelan46/Dealer.git",
    "completed_date": "2026-01-09",
    "is_featured": true,
    "created_at": "2026-01-09T14:42:12.504700+05:30",
    "updated_at": "2026-01-09T14:43:39.734624+05:30"
  }
];
